# file: tasks/install.yml -- install postgresql packages

# http://docs.ansible.com/ansible/latest/become.html#becoming-an-unprivileged-user
- name: "Stage 1: install setfacl to work support becoming a non-priveleged user"
  package: state='latest' pkg='acl'

- name: "Stage 1: install PostgreSQL on RedHat/CentOS"
  include: 'install_rhel.yml'
  when: ansible_os_family == 'RedHat'

- name: "Stage 1: install PostgreSQL on Debian/Ubuntu"
  include: 'install_deb.yml'
  when: ansible_os_family == 'Debian'

- name: 'Stage 1: install Ansible postgresql dependency package'
  package: state='latest' pkg='python-psycopg2'

